import type { WorkoutType } from '@/domain/types';

export interface ProgramExercise {
  name: string;
  sets: number;
  reps: string;
  note?: string;
}

export interface Program {
  id: string;
  name: string;
  type: WorkoutType;
  emoji: string;
  level: 'débutant' | 'intermédiaire';
  durationMinutes: number;
  description: string;
  exercises: ProgramExercise[];
  /** Séance chronométrée (HIIT, fractionné) : rounds travail/repos en secondes. */
  intervals?: { rounds: number; workSec: number; restSec: number };
  /** Catégorie d'affichage. */
  family?: 'fullbody' | 'split' | 'home' | 'hiit' | 'mobilite' | 'endurance';
}

export const PROGRAMS: Program[] = [
  {
    id: 'fullbody_a',
    name: 'Full Body A',
    type: 'gym',
    emoji: '🏋️',
    level: 'débutant',
    durationMinutes: 45,
    family: 'fullbody',
    description: 'Machines guidées, tout le corps, 3 séries par exercice. Repos 90 s.',
    exercises: [
      { name: 'Presse à cuisses', sets: 3, reps: '8-12' },
      { name: 'Développé machine (pecs)', sets: 3, reps: '8-12' },
      { name: 'Tirage vertical', sets: 3, reps: '8-12' },
      { name: 'Leg curl (ischios)', sets: 3, reps: '10-15' },
      { name: 'Élévations latérales', sets: 3, reps: '12-15' },
      { name: 'Crunch / gainage', sets: 3, reps: '12-15' },
    ],
  },
  {
    id: 'fullbody_b',
    name: 'Full Body B',
    type: 'gym',
    emoji: '🏋️',
    level: 'débutant',
    durationMinutes: 45,
    family: 'fullbody',
    description: 'À alterner avec le A. Haltères + machines.',
    exercises: [
      { name: 'Squat goblet (haltère)', sets: 3, reps: '8-12' },
      { name: 'Développé incliné haltères', sets: 3, reps: '8-12' },
      { name: 'Rowing machine / haltère', sets: 3, reps: '8-12' },
      { name: 'Fentes marchées', sets: 3, reps: '10 / jambe' },
      { name: 'Curl biceps', sets: 2, reps: '10-15' },
      { name: 'Extension triceps poulie', sets: 2, reps: '10-15' },
    ],
  },
  {
    id: 'home_a',
    name: 'Maison A (sans matériel)',
    type: 'home',
    emoji: '🏠',
    level: 'débutant',
    durationMinutes: 30,
    family: 'home',
    description: 'Poids du corps, dans une chambre d’étudiant. Repos 60 s.',
    exercises: [
      { name: 'Squats', sets: 3, reps: '12-15' },
      { name: 'Pompes (genoux ok)', sets: 3, reps: '8-12' },
      { name: 'Fentes', sets: 3, reps: '10 / jambe' },
      { name: 'Hip thrust au sol', sets: 3, reps: '15' },
      { name: 'Planche', sets: 3, reps: '30-45 s' },
      { name: 'Superman (bas du dos)', sets: 3, reps: '12' },
    ],
  },
  {
    id: 'home_b',
    name: 'Maison B (sans matériel)',
    type: 'home',
    emoji: '🏠',
    level: 'intermédiaire',
    durationMinutes: 30,
    family: 'home',
    description: 'Un peu plus intense, toujours sans matériel.',
    exercises: [
      { name: 'Squat bulgare (pied sur chaise)', sets: 3, reps: '8-10 / jambe' },
      { name: 'Pompes déclinées (pieds surélevés)', sets: 3, reps: '8-12' },
      { name: 'Dips sur chaise', sets: 3, reps: '8-12' },
      { name: 'Relevé de bassin une jambe', sets: 3, reps: '12 / jambe' },
      { name: 'Gainage latéral', sets: 3, reps: '30 s / côté' },
      { name: 'Mountain climbers', sets: 3, reps: '30 s' },
    ],
  },
  {
    id: 'ppl_push',
    name: 'Push (pecs, épaules, triceps)',
    type: 'gym',
    emoji: '🏋️',
    level: 'intermédiaire',
    durationMinutes: 55,
    family: 'split',
    description: 'Split Push / Pull / Legs, 3 à 6 séances par semaine. Repos 90 s à 2 min.',
    exercises: [
      { name: 'Développé couché', sets: 4, reps: '6-10' },
      { name: 'Développé incliné haltères', sets: 3, reps: '8-12' },
      { name: 'Développé militaire', sets: 3, reps: '8-12' },
      { name: 'Élévations latérales', sets: 3, reps: '12-15' },
      { name: 'Extension triceps poulie', sets: 3, reps: '10-15' },
      { name: 'Dips', sets: 2, reps: 'max' },
    ],
  },
  {
    id: 'ppl_pull',
    name: 'Pull (dos, biceps)',
    type: 'gym',
    emoji: '🏋️',
    level: 'intermédiaire',
    durationMinutes: 55,
    family: 'split',
    description: 'Deuxième séance du split. Tire large, tire serré, puis les bras.',
    exercises: [
      { name: 'Tractions', sets: 4, reps: '4-8' },
      { name: 'Rowing barre', sets: 4, reps: '6-10' },
      { name: 'Tirage horizontal poulie', sets: 3, reps: '10-12' },
      { name: 'Face pull', sets: 3, reps: '12-15' },
      { name: 'Curl biceps', sets: 3, reps: '10-12' },
      { name: 'Curl marteau', sets: 2, reps: '10-12' },
    ],
  },
  {
    id: 'ppl_legs',
    name: 'Legs (jambes, abdos)',
    type: 'gym',
    emoji: '🦵',
    level: 'intermédiaire',
    durationMinutes: 55,
    family: 'split',
    description: 'Troisième séance du split. La plus dure, la plus payante.',
    exercises: [
      { name: 'Squat barre', sets: 4, reps: '5-8' },
      { name: 'Soulevé de terre roumain', sets: 3, reps: '8-10' },
      { name: 'Presse à cuisses', sets: 3, reps: '10-12' },
      { name: 'Leg curl (ischios)', sets: 3, reps: '10-15' },
      { name: 'Mollets debout', sets: 3, reps: '12-20' },
      { name: 'Planche', sets: 3, reps: '45 s' },
    ],
  },
  {
    id: 'upper',
    name: 'Upper (haut du corps)',
    type: 'gym',
    emoji: '💪',
    level: 'intermédiaire',
    durationMinutes: 50,
    family: 'split',
    description: 'Split Upper / Lower, 4 séances par semaine.',
    exercises: [
      { name: 'Développé couché', sets: 4, reps: '6-10' },
      { name: 'Rowing barre', sets: 4, reps: '6-10' },
      { name: 'Développé haltères épaules', sets: 3, reps: '8-12' },
      { name: 'Tirage vertical', sets: 3, reps: '10-12' },
      { name: 'Curl biceps', sets: 2, reps: '10-15' },
      { name: 'Extension triceps poulie', sets: 2, reps: '10-15' },
    ],
  },
  {
    id: 'lower',
    name: 'Lower (bas du corps)',
    type: 'gym',
    emoji: '🦵',
    level: 'intermédiaire',
    durationMinutes: 50,
    family: 'split',
    description: 'Deuxième moitié du split Upper / Lower.',
    exercises: [
      { name: 'Squat barre', sets: 4, reps: '6-10' },
      { name: 'Soulevé de terre roumain', sets: 3, reps: '8-12' },
      { name: 'Fentes', sets: 3, reps: '10 / jambe' },
      { name: 'Hip thrust', sets: 3, reps: '10-15' },
      { name: 'Mollets debout', sets: 3, reps: '15-20' },
      { name: 'Relevé de jambes', sets: 3, reps: '10-15' },
    ],
  },
  {
    id: 'home_dumbbells',
    name: 'Maison avec haltères',
    type: 'home',
    emoji: '🏠',
    level: 'intermédiaire',
    durationMinutes: 40,
    family: 'home',
    description: 'Une paire d’haltères suffit. Full body, 3 fois par semaine.',
    exercises: [
      { name: 'Squat goblet (haltère)', sets: 3, reps: '10-15' },
      { name: 'Rowing haltère', sets: 3, reps: '10-12 / bras' },
      { name: 'Développé haltères épaules', sets: 3, reps: '10-12' },
      { name: 'Fentes', sets: 3, reps: '10 / jambe' },
      { name: 'Curl biceps', sets: 2, reps: '12-15' },
      { name: 'Extension triceps haltère', sets: 2, reps: '12-15' },
      { name: 'Planche', sets: 3, reps: '30-45 s' },
    ],
  },
  {
    id: 'hiit_20',
    name: 'HIIT 20 min',
    type: 'home',
    emoji: '⚡',
    level: 'intermédiaire',
    durationMinutes: 20,
    family: 'hiit',
    description: '8 rounds de 40 s d’effort / 20 s de repos, 2 tours. Chrono intégré. Pas de matériel.',
    intervals: { rounds: 16, workSec: 40, restSec: 20 },
    exercises: [
      { name: 'Jumping jacks', sets: 1, reps: '40 s' },
      { name: 'Squats poids du corps', sets: 1, reps: '40 s' },
      { name: 'Mountain climbers', sets: 1, reps: '40 s' },
      { name: 'Pompes', sets: 1, reps: '40 s' },
      { name: 'Fentes', sets: 1, reps: '40 s' },
      { name: 'Burpees', sets: 1, reps: '40 s' },
      { name: 'Planche', sets: 1, reps: '40 s' },
      { name: 'Corde à sauter', sets: 1, reps: '40 s (ou sur place)' },
    ],
  },
  {
    id: 'abs_10',
    name: 'Abdos & gainage 10 min',
    type: 'home',
    emoji: '🎯',
    level: 'débutant',
    durationMinutes: 10,
    family: 'home',
    description: 'À enchaîner après une séance ou seul. 30 s d’effort, 15 s de repos.',
    intervals: { rounds: 12, workSec: 30, restSec: 15 },
    exercises: [
      { name: 'Planche', sets: 1, reps: '30 s' },
      { name: 'Crunch', sets: 1, reps: '30 s' },
      { name: 'Gainage latéral', sets: 1, reps: '30 s / côté' },
      { name: 'Dead bug', sets: 1, reps: '30 s' },
      { name: 'Relevé de jambes', sets: 1, reps: '30 s' },
      { name: 'Mountain climbers', sets: 1, reps: '30 s' },
    ],
  },
  {
    id: 'mobility_15',
    name: 'Mobilité & étirements 15 min',
    type: 'home',
    emoji: '🧘',
    level: 'débutant',
    durationMinutes: 15,
    family: 'mobilite',
    description: 'Le soir ou après le sport. Respire, ne force jamais dans la douleur.',
    exercises: [
      { name: 'Chat-vache (dos)', sets: 2, reps: '10 lents' },
      { name: 'Étirement fléchisseurs de hanche', sets: 2, reps: '30 s / côté' },
      { name: 'Étirement ischios', sets: 2, reps: '30 s / jambe' },
      { name: 'Ouverture d’épaules', sets: 2, reps: '30 s' },
      { name: 'Rotation thoracique', sets: 2, reps: '8 / côté' },
    ],
  },
  {
    id: 'run_beginner',
    name: 'Course débutant (marche / course)',
    type: 'cardio',
    emoji: '🏃',
    level: 'débutant',
    durationMinutes: 30,
    family: 'endurance',
    description: 'Semaine 1 : 8 × (1 min de course, 2 min de marche). Ajoute 30 s de course chaque semaine. Chrono intégré.',
    intervals: { rounds: 8, workSec: 60, restSec: 120 },
    exercises: [
      { name: 'Échauffement marche', sets: 1, reps: '5 min' },
      { name: 'Course', sets: 8, reps: '1 min' },
      { name: 'Marche rapide', sets: 8, reps: '2 min' },
    ],
  },
  {
    id: 'bike',
    name: 'Vélo / vélo d’appartement',
    type: 'cardio',
    emoji: '🚴',
    level: 'débutant',
    durationMinutes: 40,
    family: 'endurance',
    description: 'Allure conversationnelle 30-45 min. Idéal pour récupérer entre deux séances de force.',
    exercises: [{ name: 'Vélo', sets: 1, reps: '30-45 min' }],
  },
  {
    id: 'swim',
    name: 'Natation',
    type: 'cardio',
    emoji: '🏊',
    level: 'débutant',
    durationMinutes: 40,
    family: 'endurance',
    description: 'Alterne 100 m tranquille / 50 m soutenu. Compte les longueurs, pas les calories.',
    exercises: [
      { name: 'Échauffement', sets: 1, reps: '200 m' },
      { name: 'Séries', sets: 6, reps: '100 m + 50 m' },
      { name: 'Retour au calme', sets: 1, reps: '100 m' },
    ],
  },
  {
    id: 'walk',
    name: 'Marche active',
    type: 'walk',
    emoji: '🚶',
    level: 'débutant',
    durationMinutes: 35,
    family: 'endurance',
    description: '30 à 45 min d’un bon pas. Podcast, musique, appel à un ami : ça compte.',
    exercises: [{ name: 'Marche', sets: 1, reps: '30-45 min', note: 'Un rythme où tu peux parler mais pas chanter.' }],
  },
  {
    id: 'cardio_beginner',
    name: 'Cardio débutant',
    type: 'cardio',
    emoji: '🚴',
    level: 'débutant',
    durationMinutes: 25,
    family: 'endurance',
    description: 'Vélo, elliptique ou course douce. Aucune notion de "brûler" un repas : c’est pour le cœur et l’énergie.',
    exercises: [
      { name: 'Échauffement', sets: 1, reps: '5 min' },
      { name: 'Effort modéré', sets: 1, reps: '15-20 min' },
      { name: 'Retour au calme', sets: 1, reps: '5 min' },
    ],
  },
];

export const FAMILY_LABELS: Record<NonNullable<Program['family']>, string> = { fullbody: 'Full body', split: 'Split (PPL, Upper/Lower)', home: 'Maison', hiit: 'HIIT', mobilite: 'Mobilité', endurance: 'Endurance' };

export const WORKOUT_TYPE_LABELS: Record<WorkoutType, string> = { gym: 'Salle', home: 'Maison', walk: 'Marche', cardio: 'Cardio' };
