import type { Difficulty, Equipment, Recipe, RecipeIngredient } from '@/domain/types';

/**
 * Recettes de départ : réalistes, portions généreuses, matériel minimal.
 * Les macros ne sont pas stockées ici : elles sont calculées à partir des
 * ingrédients (voir buildRecipeView), donc toujours cohérentes avec la base.
 */

type Ing = [foodId: string, grams: number, opts?: { optional?: boolean; note?: string }];

interface RecipeDef {
  id: string;
  name: string;
  emoji: string;
  description: string;
  tags: string[];
  prep: number;
  difficulty?: Difficulty;
  equipment: Equipment[];
  servings?: number;
  ingredients: Ing[];
  steps: string[];
  tip?: string;
  airfryer?: { tempC: number; minutes: number; oilGramsDefault: number };
}

const R: RecipeDef[] = [
  {
    id: 'pates_bolo',
    name: 'Pâtes bolognaise légère',
    emoji: '🍝',
    description: 'La bolo classique, version 5 % : grosse assiette, plein de protéines.',
    tags: ['plat', 'pates', 'etudiant', 'grosse-faim', 'proteine'],
    prep: 20,
    equipment: ['pan'],
    ingredients: [['pasta_raw', 110], ['ground_beef_5', 150], ['tomato_passata', 200], ['onion', 40], ['parmesan', 10, { optional: true }], ['olive_oil', 5]],
    steps: ['Lance la cuisson des pâtes dans une grande casserole d’eau salée.', 'Fais revenir l’oignon émincé dans l’huile 3 min, ajoute le steak haché et émiette-le.', 'Ajoute le coulis, sel, poivre, herbes. Laisse mijoter 8 min.', 'Mélange avec les pâtes égouttées, parmesan par-dessus.'],
    tip: 'Pour une version encore plus rassasiante, ajoute 100 g de champignons ou de courgette en dés dans la sauce.',
  },
  {
    id: 'poulet_riz_curry',
    name: 'Poulet riz curry express',
    emoji: '🍛',
    description: 'Le duo poulet/riz, relevé au curry, avec des légumes qui donnent du volume.',
    tags: ['plat', 'riz', 'poulet', 'rapide', 'etudiant', 'proteine'],
    prep: 15,
    equipment: ['pan'],
    ingredients: [['chicken_breast', 150], ['rice_raw', 80], ['broccoli', 150], ['olive_oil', 5], ['curry_powder', 5], ['coconut_milk_light', 80, { optional: true }]],
    steps: ['Cuis le riz (12 min à couvert, 1 volume de riz pour 2 d’eau).', 'Coupe le poulet en dés, fais-le dorer à la poêle avec l’huile et le curry, 6-8 min.', 'Ajoute les brocolis (surgelés ok) et le lait de coco, 4 min.', 'Sers sur le riz.'],
  },
  {
    id: 'poulet_frites_airfryer',
    name: 'Poulet & frites Air Fryer',
    emoji: '🍗',
    description: 'Frites maison croustillantes avec très peu d’huile, poulet doré au même moment.',
    tags: ['plat', 'airfryer', 'poulet', 'frites', 'grosse-faim', 'proteine'],
    prep: 25,
    equipment: ['airfryer'],
    ingredients: [['chicken_breast', 150], ['potato', 300], ['olive_oil', 8], ['ketchup', 20, { optional: true }]],
    steps: ['Coupe les pommes de terre en frites, rince-les et sèche-les bien (c’est ce qui les rend croustillantes).', 'Mélange avec l’huile, sel, paprika. 200 °C, 18-20 min en secouant à mi-cuisson.', 'Ajoute le poulet assaisonné dans le panier (ou en même temps si le panier est grand) : 190 °C, 12-14 min.', 'Ketchup à volonté raisonnable.'],
    airfryer: { tempC: 200, minutes: 20, oilGramsDefault: 8 },
    tip: 'Avec 8 g d’huile, cette assiette de 300 g de frites reste sous 350 kcal. La même chose en friteuse : plus du double.',
  },
  {
    id: 'steak_frites_airfryer',
    name: 'Steak & frites Air Fryer',
    emoji: '🥩',
    description: 'Le classique, en version qui rentre dans la journée.',
    tags: ['plat', 'airfryer', 'frites', 'grosse-faim', 'proteine', 'etudiant'],
    prep: 20,
    equipment: ['airfryer'],
    ingredients: [['ground_beef_5', 150], ['potato', 300], ['olive_oil', 8], ['ketchup', 20, { optional: true }]],
    steps: ['Frites : coupe, rince, sèche, 8 g d’huile, 200 °C 18-20 min.', 'Steak : 200 °C, 6-8 min selon la cuisson souhaitée (ou 3 min de chaque côté à la poêle).', 'Sel, poivre, ketchup.'],
    airfryer: { tempC: 200, minutes: 20, oilGramsDefault: 8 },
  },
  {
    id: 'burger_maison',
    name: 'Burger maison',
    emoji: '🍔',
    description: 'Un vrai burger, pain, fromage, sauce. Juste un steak 5 % et une portion maîtrisée.',
    tags: ['plat', 'burger', 'plaisir', 'etudiant', 'proteine'],
    prep: 15,
    equipment: ['pan'],
    ingredients: [['burger_bun', 55], ['ground_beef_5', 150], ['cheddar_slice', 20], ['ketchup', 15], ['mustard', 5, { optional: true }], ['tomato', 40, { optional: true }], ['lettuce', 20, { optional: true }], ['onion', 20, { optional: true }]],
    steps: ['Forme un steak plat, sel, poivre. Poêle bien chaude, 3 min par face, fromage sur le steak à la fin.', 'Toaste le pain 1 min dans la poêle.', 'Monte : sauce, steak, garniture.'],
    tip: 'Envie de frites avec ? Ajoute 200 g de pommes de terre Air Fryer (~220 kcal) : ça reste un repas raisonnable.',
  },
  {
    id: 'wrap_poulet',
    name: 'Wrap poulet sauce blanche',
    emoji: '🌯',
    description: 'Le wrap de kebab, version maison en 10 minutes.',
    tags: ['plat', 'wrap', 'poulet', 'rapide', 'etudiant', 'proteine'],
    prep: 10,
    equipment: ['pan'],
    ingredients: [['tortilla_wrap', 60], ['chicken_breast', 130], ['yogurt_sauce', 40], ['gruyere', 15, { optional: true }], ['lettuce', 40, { optional: true }], ['tomato', 40, { optional: true }], ['onion', 20, { optional: true }]],
    steps: ['Poulet en lamelles, épices (paprika, cumin), poêle 6-7 min.', 'Chauffe la tortilla 30 s.', 'Sauce, poulet, garniture, roule serré.'],
  },
  {
    id: 'omelette_jambon_fromage',
    name: 'Omelette jambon-fromage + pain',
    emoji: '🍳',
    description: 'Prête en 7 minutes, ultra protéinée.',
    tags: ['plat', 'rapide', 'etudiant', 'proteine', 'petit-dej'],
    prep: 7,
    equipment: ['pan'],
    ingredients: [['egg', 165, { note: '3 œufs' }], ['ham', 50], ['gruyere', 25], ['bread', 60], ['olive_oil', 3]],
    steps: ['Bats les œufs avec sel et poivre.', 'Poêle huilée à feu moyen, verse les œufs, ajoute jambon et fromage quand ça prend.', 'Plie, sers avec le pain.'],
  },
  {
    id: 'riz_curry_poulet_coco',
    name: 'Riz curry poulet coco',
    emoji: '🥥',
    description: 'Sauce onctueuse au lait de coco allégé, poivrons, gros bol.',
    tags: ['plat', 'riz', 'poulet', 'proteine', 'grosse-faim'],
    prep: 20,
    equipment: ['pan'],
    ingredients: [['chicken_breast', 150], ['rice_raw', 80], ['coconut_milk_light', 120], ['curry_powder', 8], ['bell_pepper', 120], ['onion', 40], ['olive_oil', 5]],
    steps: ['Riz : 12 min à couvert.', 'Oignon et poivron émincés dans l’huile 4 min, poulet en dés 6 min.', 'Curry + lait de coco, 5 min à feu doux. Sers sur le riz.'],
  },
  {
    id: 'pates_poulet_parmesan',
    name: 'Pâtes poulet parmesan crémeuses',
    emoji: '🧀',
    description: 'Crémeux grâce à la crème légère, parmesan pour le goût.',
    tags: ['plat', 'pates', 'poulet', 'proteine', 'grosse-faim'],
    prep: 20,
    equipment: ['pan'],
    ingredients: [['pasta_raw', 100], ['chicken_breast', 150], ['cream_light', 80], ['parmesan', 20], ['mushrooms', 100, { optional: true }], ['olive_oil', 5]],
    steps: ['Pâtes dans l’eau salée.', 'Poulet en dés à la poêle 6 min, champignons 3 min.', 'Crème + parmesan + une louche d’eau de cuisson, mélange avec les pâtes.'],
  },
  {
    id: 'croque_monsieur',
    name: 'Croque-monsieur (version pain complet)',
    emoji: '🥪',
    description: 'Deux croques, croustillants au four ou à l’Air Fryer, sans béchamel.',
    tags: ['plat', 'rapide', 'etudiant', 'plaisir', 'airfryer'],
    prep: 10,
    equipment: ['airfryer', 'pan'],
    ingredients: [['wholemeal_bread', 140, { note: '4 tranches' }], ['ham', 80], ['gruyere', 40], ['mustard', 10, { optional: true }], ['butter', 5, { optional: true }]],
    steps: ['Moutarde sur le pain, jambon, fromage, referme.', 'Air Fryer 180 °C 6-8 min (ou poêle avec un couvercle, 3 min par face).'],
    airfryer: { tempC: 180, minutes: 7, oilGramsDefault: 0 },
    tip: 'Ajoute une soupe ou 150 g de légumes à côté si tu as encore faim : quasi zéro kcal, beaucoup de volume.',
  },
  {
    id: 'pizza_tortilla',
    name: 'Pizza express sur tortilla',
    emoji: '🍕',
    description: 'Base tortilla ultra fine : croustillante en 8 minutes, moitié moins calorique qu’une pizza classique.',
    tags: ['plat', 'pizza', 'rapide', 'plaisir', 'airfryer', 'etudiant'],
    prep: 10,
    equipment: ['airfryer', 'oven'],
    ingredients: [['tortilla_wrap', 60], ['tomato_sauce', 60], ['mozzarella', 60], ['ham', 50], ['mushrooms', 50, { optional: true }]],
    steps: ['Étale la sauce sur la tortilla, garnis.', 'Air Fryer 180 °C 6-8 min ou four 220 °C 8-10 min.'],
    tip: 'Deux pizzas tortilla = une grosse faim calée pour ~800 kcal.',
  },
  {
    id: 'pizza_maison',
    name: 'Pizza maison (pâte prête)',
    emoji: '🍕',
    description: 'Une demi-pâte, garniture généreuse en protéines : la pizza rentre dans une journée normale.',
    tags: ['plat', 'pizza', 'plaisir', 'grosse-faim'],
    prep: 25,
    equipment: ['oven'],
    ingredients: [['pizza_dough', 130], ['tomato_sauce', 80], ['mozzarella', 80], ['chicken_breast_cooked', 80], ['mushrooms', 60, { optional: true }], ['bell_pepper', 50, { optional: true }]],
    steps: ['Four 220 °C. Étale la demi-pâte, sauce, garniture.', '12-15 min jusqu’à ce que le bord soit doré.'],
    tip: 'Tu peux manger une pizza ce soir : le reste de la journée, vise des repas plus légers et protéinés (skyr, poulet, légumes) sans sauter de repas.',
  },
  {
    id: 'bol_riz_micro_poulet',
    name: 'Bol riz micro-ondes poulet soja',
    emoji: '🍚',
    description: 'Zéro vaisselle : sachet de riz, poulet rôti, légumes surgelés, sauce soja.',
    tags: ['plat', 'micro-ondes', 'rapide', 'riz', 'poulet', 'etudiant', 'sans-cuisson'],
    prep: 5,
    equipment: ['microwave'],
    ingredients: [['rice_microwave', 250], ['chicken_breast_cooked', 120], ['frozen_veg_mix', 150], ['soy_sauce', 15]],
    steps: ['Légumes 4 min au micro-ondes.', 'Riz 2 min.', 'Mélange tout avec le poulet et la sauce soja.'],
  },
  {
    id: 'skyr_bowl_petit_dej',
    name: 'Bol skyr banane flocons',
    emoji: '🥣',
    description: '35 g de protéines au petit-déjeuner, sans cuisson.',
    tags: ['petit-dej', 'rapide', 'sans-cuisson', 'proteine', 'collation'],
    prep: 3,
    equipment: ['none'],
    ingredients: [['skyr', 250], ['banana', 120], ['oats', 40], ['honey', 10, { optional: true }]],
    steps: ['Tout dans un bol. C’est tout.'],
  },
  {
    id: 'porridge_banane_pb',
    name: 'Porridge banane beurre de cacahuète',
    emoji: '🥜',
    description: 'Chaud, gourmand, tient jusqu’à midi.',
    tags: ['petit-dej', 'micro-ondes', 'rapide'],
    prep: 5,
    equipment: ['microwave'],
    ingredients: [['oats', 60], ['milk_semi', 250], ['banana', 100], ['peanut_butter', 15]],
    steps: ['Flocons + lait dans un grand bol, micro-ondes 2 min 30, remue, 1 min.', 'Banane en rondelles, beurre de cacahuète.'],
  },
  {
    id: 'oeufs_brouilles_pain',
    name: 'Œufs brouillés & pain complet',
    emoji: '🍳',
    description: 'Le petit-déj salé qui cale.',
    tags: ['petit-dej', 'rapide', 'proteine'],
    prep: 6,
    equipment: ['pan', 'microwave'],
    ingredients: [['egg', 165, { note: '3 œufs' }], ['wholemeal_bread', 70], ['butter', 5]],
    steps: ['Œufs battus, poêle feu doux avec le beurre, remue jusqu’à ce que ce soit crémeux (ou micro-ondes 1 min + 30 s).', 'Sur le pain toasté.'],
  },
  {
    id: 'sandwich_poulet',
    name: 'Sandwich poulet moutarde',
    emoji: '🥖',
    description: 'Le sandwich de midi, sans cuisson.',
    tags: ['plat', 'rapide', 'sans-cuisson', 'etudiant', 'proteine'],
    prep: 5,
    equipment: ['none'],
    ingredients: [['bread', 110], ['chicken_breast_cooked', 100], ['mustard', 10], ['mayo_light', 10, { optional: true }], ['lettuce', 30, { optional: true }], ['tomato', 50, { optional: true }]],
    steps: ['Ouvre, tartine, garnis.'],
  },
  {
    id: 'thon_mais_riz',
    name: 'Riz thon maïs (sans cuisson)',
    emoji: '🐟',
    description: 'Une boîte de thon, un sachet de riz, du maïs : 5 minutes.',
    tags: ['plat', 'rapide', 'sans-cuisson', 'micro-ondes', 'riz', 'etudiant', 'proteine'],
    prep: 5,
    equipment: ['microwave'],
    ingredients: [['rice_microwave', 250], ['tuna_can', 110], ['corn_can', 80], ['mayo_light', 20], ['tomato', 60, { optional: true }]],
    steps: ['Riz 2 min au micro-ondes (ou froid).', 'Mélange avec le thon émietté, le maïs, la mayo.'],
  },
  {
    id: 'nuggets_airfryer',
    name: 'Nuggets Air Fryer & légumes',
    emoji: '🍗',
    description: 'Les nuggets surgelés, croustillants sans huile ajoutée.',
    tags: ['plat', 'airfryer', 'rapide', 'plaisir', 'etudiant'],
    prep: 12,
    equipment: ['airfryer'],
    ingredients: [['chicken_nuggets', 150], ['frozen_veg_mix', 200], ['ketchup', 20]],
    steps: ['Nuggets 190 °C 10-12 min sans huile.', 'Légumes 4 min au micro-ondes ou 12 min à l’Air Fryer avec les nuggets.'],
    airfryer: { tempC: 190, minutes: 11, oilGramsDefault: 0 },
  },
  {
    id: 'crevettes_riz_soja',
    name: 'Crevettes sautées riz légumes',
    emoji: '🍤',
    description: 'Façon wok, en 15 minutes.',
    tags: ['plat', 'riz', 'rapide', 'proteine'],
    prep: 15,
    equipment: ['pan'],
    ingredients: [['shrimp', 150], ['rice_raw', 80], ['frozen_veg_mix', 200], ['soy_sauce', 15], ['olive_oil', 5]],
    steps: ['Riz 12 min.', 'Légumes surgelés à la poêle 6 min, crevettes 3 min, sauce soja.'],
  },
  {
    id: 'cabillaud_pdt_airfryer',
    name: 'Cabillaud & pommes de terre Air Fryer',
    emoji: '🐠',
    description: 'Poisson blanc très léger, grosse portion de pommes de terre rôties.',
    tags: ['plat', 'airfryer', 'proteine', 'grosse-faim'],
    prep: 25,
    equipment: ['airfryer'],
    ingredients: [['cod', 200], ['potato', 300], ['olive_oil', 10], ['green_beans', 150, { optional: true }]],
    steps: ['Pommes de terre en cubes, huile, herbes : 200 °C 18 min.', 'Ajoute le cabillaud (citron, sel) : 180 °C 8-10 min.'],
    airfryer: { tempC: 200, minutes: 18, oilGramsDefault: 10 },
  },
  {
    id: 'saumon_riz_courgettes',
    name: 'Saumon riz courgettes',
    emoji: '🍣',
    description: 'Un pavé, du riz, des courgettes fondantes.',
    tags: ['plat', 'riz', 'proteine'],
    prep: 20,
    equipment: ['pan', 'airfryer'],
    ingredients: [['salmon', 130], ['rice_raw', 70], ['zucchini', 200], ['olive_oil', 5], ['soy_sauce', 10, { optional: true }]],
    steps: ['Riz 12 min.', 'Courgettes en dés à la poêle 8 min, saumon 4 min par face (ou Air Fryer 180 °C 10 min).'],
  },
  {
    id: 'chili_con_carne',
    name: 'Chili con carne (grosse portion)',
    emoji: '🌶️',
    description: 'Haricots rouges + bœuf 5 % : le repas le plus rassasiant de la liste.',
    tags: ['plat', 'riz', 'grosse-faim', 'proteine', 'etudiant'],
    prep: 25,
    equipment: ['pan'],
    ingredients: [['ground_beef_5', 150], ['red_beans_can', 150], ['tomato_passata', 200], ['onion', 40], ['rice_raw', 60], ['curry_powder', 5, { note: 'épices chili/cumin/paprika' }], ['olive_oil', 5]],
    steps: ['Oignon dans l’huile, bœuf émietté, épices.', 'Coulis + haricots, mijote 12 min.', 'Sur le riz.'],
    tip: 'Se prépare en double et se réchauffe très bien le lendemain.',
  },
  {
    id: 'lentilles_jambon_feta',
    name: 'Bol lentilles jambon feta',
    emoji: '🥗',
    description: 'Lentilles en conserve, jambon, feta, moutarde : froid ou tiède, aucun légume cru.',
    tags: ['plat', 'rapide', 'sans-cuisson', 'proteine', 'etudiant'],
    prep: 5,
    equipment: ['none'],
    ingredients: [['lentils_cooked', 250], ['ham', 60], ['feta', 30], ['mustard', 10], ['olive_oil', 5]],
    steps: ['Égoutte les lentilles, mélange tout, poivre.'],
  },
  {
    id: 'tofu_riz_soja',
    name: 'Tofu croustillant riz légumes',
    emoji: '🌱',
    description: 'Version végane du bol riz-soja.',
    tags: ['plat', 'riz', 'vegetarien', 'vegan', 'proteine', 'airfryer'],
    prep: 15,
    equipment: ['pan', 'airfryer'],
    ingredients: [['tofu', 150], ['rice_raw', 80], ['frozen_veg_mix', 200], ['soy_sauce', 15], ['olive_oil', 5]],
    steps: ['Tofu en cubes, sauce soja, Air Fryer 200 °C 10 min ou poêle bien chaude.', 'Riz + légumes sautés.'],
  },
  {
    id: 'quesadilla_poulet',
    name: 'Quesadilla poulet fromage',
    emoji: '🫓',
    description: 'Croustillant, fondant, 10 minutes.',
    tags: ['plat', 'wrap', 'poulet', 'rapide', 'plaisir', 'etudiant'],
    prep: 10,
    equipment: ['pan'],
    ingredients: [['tortilla_wrap', 60], ['chicken_breast_cooked', 100], ['gruyere', 35], ['bell_pepper', 50, { optional: true }], ['tomato_sauce', 30]],
    steps: ['Sauce sur une moitié de tortilla, poulet, fromage, poivron. Plie.', 'Poêle sèche 3 min par face.'],
  },
  {
    id: 'pdt_airfryer_oeufs',
    name: 'Pommes de terre rôties & œufs',
    emoji: '🥔',
    description: 'Végétarien, très rassasiant, pas cher.',
    tags: ['plat', 'airfryer', 'vegetarien', 'grosse-faim', 'etudiant'],
    prep: 22,
    equipment: ['airfryer', 'pan'],
    ingredients: [['potato', 300], ['egg', 110, { note: '2 œufs' }], ['frozen_veg_mix', 150], ['olive_oil', 8], ['gruyere', 15, { optional: true }]],
    steps: ['Pommes de terre en cubes, huile, 200 °C 18 min.', 'Œufs au plat à la poêle, légumes au micro-ondes.'],
    airfryer: { tempC: 200, minutes: 18, oilGramsDefault: 8 },
  },
  {
    id: 'skyr_fruits_rouges',
    name: 'Skyr fruits rouges miel',
    emoji: '🍓',
    description: 'Collation ou dessert : 300 g pour 250 kcal.',
    tags: ['collation', 'dessert', 'sans-cuisson', 'proteine', 'rapide'],
    prep: 2,
    equipment: ['none'],
    ingredients: [['skyr', 200], ['frozen_berries', 100], ['honey', 10]],
    steps: ['Fruits rouges 40 s au micro-ondes ou tels quels, sur le skyr.'],
  },
  {
    id: 'pancakes_proteines',
    name: 'Pancakes protéinés banane',
    emoji: '🥞',
    description: 'Sans farine : flocons, œuf, fromage blanc.',
    tags: ['petit-dej', 'proteine', 'plaisir'],
    prep: 12,
    equipment: ['pan'],
    ingredients: [['oats', 50], ['egg', 55, { note: '1 œuf' }], ['fromage_blanc_0', 100], ['banana', 80], ['whey', 15, { optional: true }], ['honey', 10, { optional: true }]],
    steps: ['Mixe tout (ou écrase la banane à la fourchette et mélange).', 'Petites louches dans une poêle antiadhésive, 2 min par face.'],
  },
  {
    id: 'gnocchi_poulet_courgette',
    name: 'Gnocchi poêlés poulet courgette',
    emoji: '🥟',
    description: 'Gnocchi dorés à la poêle, sans les bouillir.',
    tags: ['plat', 'rapide', 'poulet', 'etudiant'],
    prep: 15,
    equipment: ['pan'],
    ingredients: [['gnocchi', 250], ['chicken_breast', 130], ['zucchini', 150], ['parmesan', 15], ['olive_oil', 5]],
    steps: ['Poulet en dés à la poêle 6 min, réserve.', 'Gnocchi directement dans la poêle avec l’huile, 6 min en remuant, courgette en dés.', 'Remets le poulet, parmesan.'],
  },
  {
    id: 'lasagnes_ameliorees',
    name: 'Lasagnes surgelées améliorées',
    emoji: '🍱',
    description: 'La barquette du placard + des haricots verts : plus de volume, même effort.',
    tags: ['plat', 'micro-ondes', 'rapide', 'plaisir', 'etudiant'],
    prep: 8,
    equipment: ['microwave'],
    ingredients: [['frozen_lasagna', 300], ['green_beans', 200], ['gruyere', 10, { optional: true }]],
    steps: ['Lasagnes au micro-ondes selon le paquet.', 'Haricots verts 4 min. Sel, poivre.'],
    tip: 'Ajouter des légumes à un plat surgelé double le volume de l’assiette pour ~60 kcal.',
  },
  {
    id: 'pizza_surgelee_equilibree',
    name: 'Pizza surgelée + légumes',
    emoji: '🍕',
    description: 'La pizza entière, pas la moitié. Avec des légumes à côté si tu aimes.',
    tags: ['plat', 'pizza', 'plaisir', 'grosse-faim'],
    prep: 15,
    equipment: ['oven', 'airfryer'],
    ingredients: [['frozen_pizza', 350], ['green_beans', 150, { optional: true }]],
    steps: ['Four selon le paquet.', 'Légumes 4 min au micro-ondes.'],
    tip: 'Une pizza ≈ 840 kcal : ça rentre dans une journée à 2 000 kcal avec un petit-déj protéiné et un déjeuner léger. Aucune compensation nécessaire.',
  },
  {
    id: 'wrap_croustillant_airfryer',
    name: 'Wrap croustillant Air Fryer',
    emoji: '🌯',
    description: 'Wrap roulé, passé à l’Air Fryer : croustillant comme au fast-food.',
    tags: ['plat', 'airfryer', 'wrap', 'poulet', 'rapide', 'plaisir'],
    prep: 12,
    equipment: ['airfryer'],
    ingredients: [['tortilla_wrap', 60], ['chicken_breast_cooked', 120], ['gruyere', 25], ['tomato_sauce', 30], ['bell_pepper', 50, { optional: true }]],
    steps: ['Garnis, roule bien serré, replie les bords.', 'Air Fryer 190 °C 6-8 min, pliure dessous.'],
    airfryer: { tempC: 190, minutes: 7, oilGramsDefault: 0 },
  },
  {
    id: 'boeuf_pdt_poelee',
    name: 'Steak, pommes de terre & poêlée',
    emoji: '🍽️',
    description: 'L’assiette complète du soir, une seule poêle.',
    tags: ['plat', 'proteine', 'grosse-faim'],
    prep: 25,
    equipment: ['pan'],
    ingredients: [['beef_steak', 150], ['potato', 300], ['frozen_veg_mix', 150], ['olive_oil', 8]],
    steps: ['Pommes de terre en dés 5 min au micro-ondes, puis à la poêle avec l’huile 10 min.', 'Ajoute la poêlée 5 min. Steak 2-3 min par face.'],
  },
  {
    id: 'semoule_poulet_legumes',
    name: 'Semoule poulet légumes (couscous express)',
    emoji: '🍲',
    description: 'La semoule gonfle en 5 minutes, le reste cuit pendant ce temps.',
    tags: ['plat', 'rapide', 'poulet', 'proteine', 'etudiant'],
    prep: 15,
    equipment: ['pan', 'microwave'],
    ingredients: [['couscous_raw', 80], ['chicken_breast', 150], ['frozen_veg_mix', 200], ['tomato_passata', 100], ['curry_powder', 5, { note: 'ras el hanout' }], ['olive_oil', 5]],
    steps: ['Semoule + même volume d’eau bouillante, couvre 5 min, égrène.', 'Poulet en dés + légumes + coulis + épices à la poêle 10 min.'],
  },
  {
    id: 'riz_cantonais_etudiant',
    name: 'Riz cantonais étudiant',
    emoji: '🥡',
    description: 'Riz, œufs, petits pois, jambon, sauce soja : 8 minutes.',
    tags: ['plat', 'riz', 'rapide', 'etudiant', 'proteine'],
    prep: 8,
    equipment: ['pan'],
    ingredients: [['rice_microwave', 250], ['egg', 110, { note: '2 œufs' }], ['peas', 80], ['ham', 60], ['soy_sauce', 15], ['olive_oil', 5]],
    steps: ['Œufs brouillés à la poêle, réserve.', 'Riz + petits pois + jambon dans la poêle 3 min, sauce soja, œufs.'],
  },
  {
    id: 'pdt_jambon_fromage_blanc',
    name: 'Pommes de terre micro-ondes, jambon, fromage blanc',
    emoji: '🥔',
    description: 'Le plat 3 ingrédients quand tu n’as pas envie de cuisiner.',
    tags: ['plat', 'micro-ondes', 'rapide', 'etudiant', 'grosse-faim'],
    prep: 10,
    equipment: ['microwave'],
    ingredients: [['potato', 350], ['ham', 80], ['fromage_blanc_0', 120], ['gruyere', 20, { optional: true }], ['mustard', 5, { optional: true }]],
    steps: ['Pommes de terre piquées, 8-9 min au micro-ondes (retourne à mi-temps).', 'Ouvre, fromage blanc + moutarde + ciboulette, jambon, fromage.'],
  },
  {
    id: 'yaourt_grec_chocolat',
    name: 'Yaourt grec, chocolat noir & banane',
    emoji: '🍫',
    description: 'Le dessert du soir.',
    tags: ['dessert', 'collation', 'sans-cuisson', 'plaisir', 'rapide'],
    prep: 2,
    equipment: ['none'],
    ingredients: [['greek_yogurt_0', 200], ['dark_chocolate', 20], ['banana', 100]],
    steps: ['Chocolat concassé sur le yaourt et la banane.'],
  },
  {
    id: 'smoothie_proteine',
    name: 'Smoothie protéiné banane',
    emoji: '🥤',
    description: 'À boire : 40 g de protéines en 2 minutes.',
    tags: ['collation', 'petit-dej', 'rapide', 'sans-cuisson', 'proteine'],
    prep: 3,
    equipment: ['none'],
    ingredients: [['milk_semi', 250], ['banana', 120], ['whey', 30], ['oats', 30], ['peanut_butter', 10, { optional: true }]],
    steps: ['Mixe. Sans mixeur : shaker, en écrasant bien la banane.'],
  },
  {
    id: 'tartines_pb_banane',
    name: 'Tartines beurre de cacahuète banane',
    emoji: '🍌',
    description: 'Petit-déj sucré, rapide.',
    tags: ['petit-dej', 'rapide', 'sans-cuisson'],
    prep: 3,
    equipment: ['none'],
    ingredients: [['wholemeal_bread', 70], ['peanut_butter', 20], ['banana', 100]],
    steps: ['Tartine, tranche, mange.'],
  },
  {
    id: 'oeufs_plat_frites',
    name: 'Œufs au plat & frites Air Fryer',
    emoji: '🍟',
    description: 'Végétarien, plaisir, moins de 550 kcal.',
    tags: ['plat', 'airfryer', 'frites', 'vegetarien', 'etudiant', 'plaisir'],
    prep: 22,
    equipment: ['airfryer', 'pan'],
    ingredients: [['potato', 300], ['egg', 110, { note: '2 œufs' }], ['olive_oil', 8], ['ketchup', 15, { optional: true }]],
    steps: ['Frites : 200 °C 18-20 min.', 'Œufs au plat à la poêle, 3 min.'],
    airfryer: { tempC: 200, minutes: 20, oilGramsDefault: 8 },
  },
  {
    id: 'dinde_pates_tomate',
    name: 'Escalope de dinde, pâtes sauce tomate',
    emoji: '🍝',
    description: 'Simple, protéiné, gros volume.',
    tags: ['plat', 'pates', 'proteine', 'etudiant'],
    prep: 15,
    equipment: ['pan'],
    ingredients: [['turkey_escalope', 150], ['pasta_raw', 100], ['tomato_sauce', 150], ['parmesan', 10, { optional: true }], ['olive_oil', 5]],
    steps: ['Pâtes dans l’eau salée.', 'Escalope 4 min par face, sauce tomate réchauffée dans la même poêle.'],
  },
  {
    id: 'wrap_thon',
    name: 'Wrap thon maïs',
    emoji: '🌯',
    description: 'Sans cuisson, 5 minutes, à emporter.',
    tags: ['plat', 'wrap', 'rapide', 'sans-cuisson', 'etudiant', 'proteine'],
    prep: 5,
    equipment: ['none'],
    ingredients: [['tortilla_wrap', 60], ['tuna_can', 110], ['mayo_light', 15], ['corn_can', 50], ['lettuce', 30, { optional: true }]],
    steps: ['Mélange thon, mayo, maïs. Roule.'],
  },
  {
    id: 'wrap_houmous_vegan',
    name: 'Wrap houmous pois chiches poivron',
    emoji: '🌯',
    description: 'Végane, croquant, rassasiant.',
    tags: ['plat', 'wrap', 'vegetarien', 'vegan', 'rapide', 'sans-cuisson'],
    prep: 7,
    equipment: ['none'],
    ingredients: [['tortilla_wrap', 60], ['hummus', 60], ['chickpeas_can', 80], ['bell_pepper', 60], ['spinach', 40, { optional: true }]],
    steps: ['Tartine le houmous, ajoute pois chiches écrasés, poivron en lanières.'],
  },
  {
    id: 'kebab_bowl',
    name: 'Bol kebab poulet maison',
    emoji: '🥙',
    description: 'Le goût du kebab : poulet épicé, sauce blanche, pain, oignon.',
    tags: ['plat', 'poulet', 'plaisir', 'grosse-faim', 'proteine'],
    prep: 15,
    equipment: ['pan', 'airfryer'],
    ingredients: [['chicken_breast', 160], ['bread', 90], ['yogurt_sauce', 50], ['onion', 30], ['tomato', 60, { optional: true }], ['lettuce', 40, { optional: true }], ['olive_oil', 5]],
    steps: ['Poulet en lamelles, paprika, cumin, ail. Poêle très chaude 7 min ou Air Fryer 200 °C 10 min.', 'Pain toasté, sauce, oignon.'],
  },
  {
    id: 'cordon_bleu_puree',
    name: 'Cordon bleu, pommes de terre & haricots',
    emoji: '🍽️',
    description: 'Le cordon bleu du supermarché, avec une vraie assiette autour.',
    tags: ['plat', 'airfryer', 'plaisir', 'etudiant', 'rapide'],
    prep: 15,
    equipment: ['airfryer', 'microwave'],
    ingredients: [['cordon_bleu', 100], ['potato', 250], ['green_beans', 150], ['butter', 5, { optional: true }]],
    steps: ['Cordon bleu Air Fryer 190 °C 12 min (ou poêle).', 'Pommes de terre 7 min au micro-ondes, écrasées avec le beurre. Haricots 4 min.'],
    airfryer: { tempC: 190, minutes: 12, oilGramsDefault: 0 },
  },
  {
    id: 'poulet_pdt_legumes_airfryer',
    name: 'Poulet, patate douce & légumes Air Fryer',
    emoji: '🍠',
    description: 'Tout dans le panier, 20 minutes.',
    tags: ['plat', 'airfryer', 'poulet', 'proteine', 'grosse-faim'],
    prep: 22,
    equipment: ['airfryer'],
    ingredients: [['chicken_thigh', 180], ['sweet_potato', 250], ['broccoli', 150], ['olive_oil', 8]],
    steps: ['Patate douce en cubes + huile + paprika : 200 °C 10 min.', 'Ajoute le poulet et le brocoli : 190 °C 12 min.'],
    airfryer: { tempC: 200, minutes: 22, oilGramsDefault: 8 },
  },
];

export const SEED_RECIPES: Recipe[] = R.map((d) => ({
  id: d.id,
  name: d.name,
  emoji: d.emoji,
  description: d.description,
  tags: d.tags,
  prepMinutes: d.prep,
  difficulty: d.difficulty ?? (d.prep <= 10 ? 'easy' : d.prep <= 20 ? 'easy' : 'medium'),
  equipment: d.equipment,
  servings: d.servings ?? 1,
  instructions: d.steps,
  tip: d.tip,
  airfryer: d.airfryer,
}));

export const SEED_INGREDIENTS: RecipeIngredient[] = R.flatMap((d) =>
  d.ingredients.map(([foodId, grams, opts], i) => ({ id: `${d.id}__${i}`, recipeId: d.id, foodId, grams, optional: opts?.optional, note: opts?.note })),
);
